# Generated by Django 5.2.1 on 2025-05-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_photo', models.ImageField(upload_to='course_photo')),
                ('cc_name', models.CharField()),
                ('fee', models.PositiveIntegerField()),
                ('c_note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_photo', models.ImageField(upload_to='teacher_photo')),
                ('c_name', models.CharField()),
                ('course', models.CharField()),
                ('t_note', models.TextField()),
            ],
        ),
    ]
