# Generated by Django 5.2.1 on 2025-05-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cc_name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='c_name',
            new_name='t_name',
        ),
    ]
