# Generated by Django 5.2.1 on 2025-05-17 03:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_rename_cc_name_course_c_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
