# Generated by Django 5.2.1 on 2025-05-17 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_course_c_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='t_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
